### ISSUE TITLE
Feature Request: New Frontend or Compatibility with Google Sheets

### ISSUE THREAD

**Issue by cyon1c** [AndyGlx/FullControl-GCode-Designer#1]
Hi! I am very interested in Full Control GCode, however, I do not intend to pay for a Microsoft Excel subscription just to use this. It would be great to see a compatible version for Google Sheets, or have a standalone app bundle for this with it's own frontend. Thanks for the software!

**Comment by AndyGlx** [comment]
Hey, thanks for your comment. A standalone version is definitely under consideration and will be the long-term plan if people like the software. I'm currently seeing which aspects people like/use so that future development can be best chosen. Although Google sheets is probably not going to be considered due to it using a different language for programming, open office is a possible option for a reasonably early port.

**Comment by alecperkins** [comment]
If you have a Mac, you can download Excel from the AppStore and use it in read-only mode for free, without a subscription. There may be an equivalent for Windows?

I used the read-only Mac version to export the VB modules and am currently experimenting with making them accessible via a browser-based UI. Nothing substantial yet but I can see there’s a lot of potential!

**Comment by AndyGlx** [comment]
A browser version would be great! Let me know if you need any help figuring out any of the VBA or to bounce ideas off for a UI or whatever. There's a lot of functionality built in that I haven't yet made tutorials for, like Boolean inclusion/exclusion criteria for features included in 'Repeat rules'. So these might not make complete sense. I'd definitely recommend focusing on including some critical features for an initially simplified version. There's not a lot of action on the reddit page yet (reddit/r/fullcontrol) but it could be a good place to ask what people think is most important to include. Thanks for all the interest!!

**Comment by HaasNL2** [comment]
This also doesn't work on libreoffice! Which can run macro's! Would be way more useful if it runs on free Office!

**Comment by AndyGlx** [comment]
Yep I only developed it for Excel. But it's open source so the VBA code is available for people to adapt it to Excel equivalents. I'd help with that and it would be great, but I won't be able to do it personally

**Comment by HaasNL2** [comment]
That is a bummer! IT did run on LibreCAD but gave me an error I don't know VBA so it wouldn't be possible for me to do very easily. I probably would just keep using sverchok in Blender.

**Comment by AndyGlx** [comment]
Yeh I don't know librecad. It will be more accessible in future though

**Comment by jjeffregeiringer** [comment]
> 
> 
> This also doesn't work on libreoffice! Which can run macro's! Would be way more useful if it runs on free Office!

Just want to say hello and throw my support behind a libreoffice port. I would be willing to contribute on such a project, but I also don't know a ton of VBA. Right now it's throwing errors on the very long ElseIf section around lines 900-1100; seems to have lost track of the thread of intentations or something.

Regardless, cheers and thanks for the good work!

**Comment by AndyGlx** [comment]
Thanks!

Currently working on a standalone version that wouldn't need Excel or libreoffice. If that goes well, there won't be a need for a libreoffice version. I'll keep people posted (on here/reddit/my website) when we have a working version 👍

**Comment by HaasNL2** [comment]
That is awesome Andy, I would totally understand if you want to make some money with it too. Don't sell out to Autodesk tho ;)

**Comment by AndyGlx** [comment]
Haha no plans for that :) currently intending to make it as open-source or at least somehow very open if not fully open-source. I'm really focusing on functionality for the time being

**Comment by AndyGlx** [comment]
@cilynx, haven't been able to look yet due to work commitments but will soon and will publicise it as soon as it's all checked / finished!

**Comment by chasedaigle** [comment]
I am still very interested in seeing a standalone version.  Would really like to use this software but do not have Excel

**Comment by AndyGlx** [comment]
It's coming 👍  took a while to get the revised version sorted properly since the concept shifted a bit, but now it's getting finished up and you won't need Excel to use it

**Comment by chasedaigle** [comment]
Don't mean to rush you at all just want to voice my interest in the project!

**Comment by Critical11** [comment]
+1

**Comment by AndyGlx** [comment]
Absolutely! Thanks for your interest. I do need some rushing though! Gonna be v happy when I release it ☺

**Comment by jjeffregeiringer** [comment]
+1! +1!!

**Comment by AndyGlx** [comment]
Python version of FullControl is out! 

https://github.com/FullControlXYZ/fullcontrol
