### ISSUE TITLE
Absolute extrusion mode

### ISSUE THREAD

**Issue by joe-ercolino** [AndyGlx/FullControl-GCode-Designer#10]
Hi

It is possible to produce g-code in absolute extrusion mode? My printer (FlashForge Adventurer 3) doesn't support relative extrusion mode.

Thanks

**Comment by AndyGlx** [comment]
It's possible, but takes some tweaking to the VBA or to the GCode format and I haven't tested if those tweaks cause any unintended issues with any of the functions I. FullControl, so use caution if you do it. There's a brief discussion on options here:

https://www.reddit.com/r/FullControl/comments/potc9w/extrusion_mode_relative_to_absolute/?utm_medium=android_app&utm_source=share
