### ISSUE TITLE
Will not open on my mac

### ISSUE THREAD

**Issue by ajvdmeij** [AndyGlx/FullControl-GCode-Designer#12]
Hello Andy, sorry to disturb you but I would like to ask if I am the only one where FCGCD won't open on my macbook (Air 2020 M1, macOS Monterey). It says that the file is corrupt. I tried to open it on a very old (9 years) windows laptop with Excel 2004 but that wouldn't open either, displaying the same error.

Do I have to wait for the Python version (september?) or is there anyone who can help me out?

Thanks in advance!

**Comment by AndyGlx** [comment]
Hi, I'm not sure about whether it works in Excel 2004, but if it's saying corrupt file, maybe try downloading it again, or downloading one of the parametric designs. They're basically the same, but with some extra designs included, but maybe there's some strange incompatiblility going on so trying anything might help. People have used it on a mac though. And yep Sep latest 👍

**Comment by ajvdmeij** [comment]
Hi Andy, thanks for the ultra fast reply! I tried another file, and it shows the same error: "_Excel cannot open the file 'filename.xlsm' because the file format or file extension is not valid. Verify that the file has not been corrupted and that the file extension matches the format of the file._"  Another .xlsm file did work fine. Maybe a recent (excel for mac) update got a bit tighter in security.

**Comment by ajvdmeij** [comment]
Hi Andy, it turned out, I made a mistake (not very used to download things here, on git. Sorry for taking your time. And thanks for the software!

**Comment by AndyGlx** [comment]
Ah cool. Yeh it took me a while to figure out how to download things too. Hope you find FullControl useful!
