### ISSUE TITLE
3D print seems to stop after the printing part is done, but the commands aren't.

### ISSUE THREAD

**Issue by aapolipponen** [AndyGlx/FullControl-GCode-Designer#13]
In my airfoil system, after the print is done there is a travel move to move z up by a set amount. That is done using this:
```
## Move extruder up a set amount (Default = 25) after 3D print is done.
Z_hop = 25
steps.append(fc.Extruder(on=False))
steps.append(fc.Point(z=+Z_hop))
```
The move is added to the steps just before the fc.transforms for plotting and gcode. The first transform is for plotting and the second is for saving gcode. The travel move seems to be in the plot but it doesn't show up in the gcode.

**Comment by fullcontrol-xyz** [comment]
This is in relation to the python version of FullControl (https://github.com/FullControlXYZ/fullcontrol)

I can answer here though. I'm not sure why it would be in the plot and no in gcode, so share some more info about the exact order of your commands in python if that issue still exists.

However, I think you probably want to define the last point to be relative to the highest point in the path. Probably something like:

```python
steps.append(fc.Point(z=max_height+Z_hop))
```

**Comment by aapolipponen** [comment]
Oh, sorry. I will try that out and inform you it works.

**Comment by AndyGlx** [comment]
Confirmation received that the above code revision worked
