### ISSUE TITLE
Can't mail to you at info@fullcontrolgcode.com

### ISSUE THREAD

**Issue by theahadev** [AndyGlx/FullControl-GCode-Designer#14]
Hello, when i tried to mail to you, it gives this error:
https://postmaster.1und1.de/en/case?c=r1503&i=ip&v=209.85.208.46&r=1MwzEr-1ttTLQ0pXH-00yQvf
![image](https://github.com/user-attachments/assets/7d13cfa4-5faf-40f8-a07e-1ffd1c63288a)

I know this isn't the correct place to talk about this but i coudn't find you anywhere else :(

Also, here is the mail i tried to send you:

>Hi, me again.
I want to know if it is possible to use the 3d printed bolts and nuts as leadscrews for a 3d printer?
If so, has anyone done it?
I want to make a mini 3d printer (i used the STL's in this video: https://www.youtube.com/watch?v=5HvFPYaVtQs and modded them) using dvd motors in the X and the Y axis, but I don't want my Z axis to be too short, and it isn't very easy to find leadscrews that are shorter than 150 mm here. I think the resolution wouldn't be affected that much; even if it did, I think we can change the tolerances a bit. But I want to be sure, that's why I am asking you. You don't need to rush your answer, i am more than happy to wait it :D

**Comment by arifbalik** [comment]
FullControl-GCode-Designer has nothing to do with 3d printer design. You can use this tool to generate gcode to use in your printer

**Comment by theahadev** [comment]
> FullControl-GCode-Designer has nothing to do with 3d printer design. You can use this tool to generate gcode to use in your printer

I know, i already used it for a few other things and i now want to use it for generating M8 bolts, but i want to know if the tolerances would be good enough

**Comment by arifbalik** [comment]
Again FCG has nothing to do with tolerances, it will be directly related to your hardware setup and the requirements of your application.

**Comment by fullcontrol-xyz** [comment]
Yeh, for leadscrews you really want machined components rather than 3D printed. Perhaps if you went for much larger than M8, then the tolerances (of the process) would be less critical, but that would introduce other issues.

And because I can't write a comment without saying FullControl is amazing... doing a custom print path (plus intricate non-geometric control), like FullControl allows, would let you to print the best possible bolts, but the point here is 'best possible' from a 3D printer is not as good as machined components.

**Comment by theahadev** [comment]
> Yeh, for leadscrews you really want machined components rather than 3D printed. Perhaps if you went for much larger than M8, then the tolerances (of the process) would be less critical, but that would introduce other issues.
> 
> And because I can't write a comment without saying FullControl is amazing... doing a custom print path (plus intricate non-geometric control), like FullControl allows, would let you to print the best possible bolts, but the point here is 'best possible' from a 3D printer is not as good as machined components.

Thanks, i will post it once it's done! Also, don't forget the mail quota😄

**Comment by fullcontrol-xyz** [comment]
Thanks very much for that, and the reminder! I didn't notice cos I always use Outlook as opposed to the Web email interface and Outlook doesn't say mail limits 🤦

Sorted now. Shame I probably missed a £billions investment request from Elon
