### ISSUE TITLE
Bottom layer

### ISSUE THREAD

**Issue by Astroghost-Francois** [AndyGlx/FullControl-GCode-Designer#2]
Hi ,
thanks for your excellent work !
Is it posible to add a function for generating one or more bottom layer ?

**Comment by AndyGlx** [comment]
Thanks! It is possible, but it needs a more complicated design where you have a few layers of the base-layer print path before starting the vase print path. I do intent to implement it soon, likely in a revised version of the parametric files with a few extra parameters for more control over the geometry along with lots of demo parameter sets with images of the respective printed parts. I'll definitely post on Instagram when this is done.

**Comment by Astroghost-Francois** [comment]
Great news , thanks.
