### ISSUE TITLE
Feature Request: load vector 2D graphics.

### ISSUE THREAD

**Issue by NGC869** [AndyGlx/FullControl-GCode-Designer#7]
Hi,
it would be really nice letting FullControl import/read bi-dimensional vector graphics (ex. SVG format), in order to translate it into layer paths.
This feature would be extremely usefull, because not always we just use pure math to create drawings.
Thank you!

**Comment by AndyGlx** [comment]
Thanks for your comment. I'll make sure this is possible in the next version of FullControl, which is rapidly being developed (in Python)!

**Comment by NGC869** [comment]
Thank you AndyGlx for your reply and obviously for all your work!

Let me also suggest you to consider also the implementation of the LINDENMAYER system, a truly simple yet powerfull way to draw (mainly fractal) patterns.

73!

**Comment by AndyGlx** [comment]
Very interesting. This will definitely be possible too!

**Comment by AndyGlx** [comment]
Python version of FullControl is out:

https://github.com/FullControlXYZ/fullcontrol

If you look for python scripts to inspect a vector graphics file, it's easy to include any points you like in a design. Same with bezier curves, etc.
